//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Windows.Forms;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace Company.DSLBootstrap
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class DSLBootstrapToolboxHelper : DSLBootstrapToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new DSLBootstrapToolboxHelper.
		/// </summary>
		public DSLBootstrapToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Justification = "The store is disposed on domain shut down")]
	public abstract class DSLBootstrapToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify DSLBootstrap toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "DSLBootstrap.1.0";

	
		private global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem> toolboxItemCache = new global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem>();
		private DslModeling::Store toolboxStore;
		
		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new DSLBootstrapToolboxHelperBase.
		/// </summary>
		protected DSLBootstrapToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::Company.DSLBootstrap.DSLBootstrapDomainModel.SingletonResourceManager.GetString("DSLBootstrapToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 25;
			}
		}
		

		/// <summary>
		/// Returns a list of custom toolbox items to be added dynamically
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}

		/// <summary>
		/// Returns instance of ModelingToolboxItem based on specified name.
		/// This method must be called from within a Transaction. Failure to do so will result in an exception
		/// </summary>
		/// <param name="itemId">unique name of desired ToolboxItem</param>
		/// <param name="store">Store to perform the operation against</param>
		/// <returns>An instance of ModelingToolboxItem if the itemId can be resolved, null otherwise</returns>
		public virtual DslDesign::ModelingToolboxItem GetToolboxItem(string itemId, DslModeling::Store store)
		{
			DslDesign::ModelingToolboxItem result = null;
			if (string.IsNullOrEmpty(itemId))
			{
				return null;
			}
			if (store == null)
			{
				return null;
			}
			global::System.Resources.ResourceManager resourceManager = global::Company.DSLBootstrap.DSLBootstrapDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			switch(itemId)
			{
				case "Company.DSLBootstrap.ButtonToolboxItem":
					// Add Button shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.ButtonToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ButtonToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ButtonToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Button", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ButtonToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.EditButton.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.TableFormalToolboxItem":
					// Add TableFormal shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.TableFormalToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TableFormalToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TableFormalToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"TableFormal", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TableFormalToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.TableFormal.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.InnerFormalToolboxItem":
					// Add InnerFormal shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.InnerFormalToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("InnerFormalToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("InnerFormalToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"InnerFormal", // F1 help keyword for the toolbox item.
						resourceManager.GetString("InnerFormalToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.InnerFormal.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.EntradaToolboxItem":
					// Add Entrada shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.EntradaToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EntradaToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EntradaToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Entrada", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EntradaToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.Entrada.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.EtiquetaToolboxItem":
					// Add Etiqueta shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.EtiquetaToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EtiquetaToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EtiquetaToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Etiqueta", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EtiquetaToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.Etiquetas.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.BarradeprogresooToolboxItem":
					// Add Barradeprogresoo shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.BarradeprogresooToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						6, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("BarradeprogresooToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("BarradeprogresooToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Barradeprogresoo", // F1 help keyword for the toolbox item.
						resourceManager.GetString("BarradeprogresooToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.Barradeprogreso.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.FormularioFormalToolboxItem":
					// Add FormularioFormal shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.FormularioFormalToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						7, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("FormularioFormalToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("FormularioFormalToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"FormularioFormal", // F1 help keyword for the toolbox item.
						resourceManager.GetString("FormularioFormalToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.FormularioFormal.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.FormularioBonitoToolboxItem":
					// Add FormularioBonito shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.FormularioBonitoToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						8, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("FormularioBonitoToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("FormularioBonitoToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"FormularioBonito", // F1 help keyword for the toolbox item.
						resourceManager.GetString("FormularioBonitoToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.FormularioBonito.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.CheckBoxToolboxItem":
					// Add CheckBox shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.CheckBoxToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						9, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("CheckBoxToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("CheckBoxToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"CheckBox", // F1 help keyword for the toolbox item.
						resourceManager.GetString("CheckBoxToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.CheckBox.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.ItemToolboxItem":
					// Add Item shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.ItemToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						10, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ItemToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ItemToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Item", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ItemToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.EditItem.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.ColumnaToolboxItem":
					// Add Columna shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.ColumnaToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						11, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ColumnaToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ColumnaToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Columna", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ColumnaToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.Columnas.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.RenglonToolboxItem":
					// Add Renglon shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.RenglonToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						12, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("RenglonToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("RenglonToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Renglon", // F1 help keyword for the toolbox item.
						resourceManager.GetString("RenglonToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.Renglones.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.InnerBonitoToolboxItem":
					// Add InnerBonito shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.InnerBonitoToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						13, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("InnerBonitoToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("InnerBonitoToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"InnerBonito", // F1 help keyword for the toolbox item.
						resourceManager.GetString("InnerBonitoToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.InnerBonito.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.TableBonitaToolboxItem":
					// Add TableBonita shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.TableBonitaToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						14, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TableBonitaToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TableBonitaToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"TableBonita", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TableBonitaToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.TableBonita.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.RadioButtonToolboxItem":
					// Add RadioButton shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.RadioButtonToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						15, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("RadioButtonToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("RadioButtonToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"RadioButton", // F1 help keyword for the toolbox item.
						resourceManager.GetString("RadioButtonToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.RadioButton.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.TextRowToolboxItem":
					// Add TextRow shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.TextRowToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						16, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("TextRowToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TextRowToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"TextRow", // F1 help keyword for the toolbox item.
						resourceManager.GetString("TextRowToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.TextRow.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.SelectItemToolboxItem":
					// Add SelectItem shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.SelectItemToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						17, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("SelectItemToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("SelectItemToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"SelectItem", // F1 help keyword for the toolbox item.
						resourceManager.GetString("SelectItemToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.Select.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.ColumnaRenglonToolboxItem":
					// Add ColumnaRenglon shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.ColumnaRenglonToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						18, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ColumnaRenglonToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ColumnaRenglonToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ColumnaRenglon", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ColumnaRenglonToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.ColumnaRenglon.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.ButtonPrimaryToolboxItem":
					// Add ButtonPrimary shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.ButtonPrimaryToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						19, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ButtonPrimaryToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ButtonPrimaryToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ButtonPrimary", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ButtonPrimaryToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.ButtonPrimary.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.ButtonWarningToolboxItem":
					// Add ButtonWarning shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.ButtonWarningToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						20, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ButtonWarningToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ButtonWarningToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ButtonWarning", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ButtonWarningToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.ButtonWarning.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.ButtonSuccessToolboxItem":
					// Add ButtonSuccess shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.ButtonSuccessToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						21, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ButtonSuccessToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ButtonSuccessToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ButtonSuccess", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ButtonSuccessToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.ButtonSuccess.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.ButtonInfoToolboxItem":
					// Add ButtonInfo shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.ButtonInfoToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						22, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ButtonInfoToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ButtonInfoToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ButtonInfo", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ButtonInfoToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.ButtonInfo.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.ButtonDangerToolboxItem":
					// Add ButtonDanger shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.ButtonDangerToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						23, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ButtonDangerToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ButtonDangerToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ButtonDanger", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ButtonDangerToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.ButtonDanger.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.EntradaEmailToolboxItem":
					// Add EntradaEmail shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.EntradaEmailToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						24, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EntradaEmailToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EntradaEmailToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EntradaEmail", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EntradaEmailToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.EntradaEmail.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "Company.DSLBootstrap.EntradaPasswordToolboxItem":
					// Add EntradaPassword shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"Company.DSLBootstrap.EntradaPasswordToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						25, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EntradaPasswordToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EntradaPasswordToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Company.DSLBootstrap.DSLBootstrapToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DSLBootstrapToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EntradaPassword", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EntradaPasswordToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Company.DSLBootstrap.EntradaPassword.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				default:
					break;
			} // end switch
			
			return result;
		}
		

		/// <summary>
		/// The store toe be used for all the toolbox item creation
		/// </summary>
		protected DslModeling::Store ToolboxStore
		{
			get
			{ 
				if (toolboxStore==null)
				{
					toolboxStore = new DslModeling::Store(this.ServiceProvider);
					EventHandler StoreCleanUp = (o, e) =>
					{
						//Since Store implements IDisposable, we need to dispose it when we're finished
						if (this.toolboxStore != null)
						{
							this.toolboxStore.Dispose();
						}
						this.toolboxStore = null;
					};
					//There is no DomainUnload event for the default AppDomain, so we listen for both ProcessExit and DomainUnload
					AppDomain.CurrentDomain.ProcessExit += new EventHandler(StoreCleanUp);
					AppDomain.CurrentDomain.DomainUnload += new EventHandler(StoreCleanUp);
					
					//load the domain model
					toolboxStore.LoadDomainModels(typeof(global::Company.DSLBootstrap.DSLBootstrapDomainModel));
					
				}
				return toolboxStore;
			}
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" returns the the toolbox item using cached dictionary
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve</param>
		private DslDesign::ModelingToolboxItem GetToolboxItem(string itemId)
		{
			DslDesign::ModelingToolboxItem item = null;

			if (!this.toolboxItemCache.TryGetValue(itemId, out item))
			{
				DslModeling::Store store = this.ToolboxStore;
				
				// Open transaction so we can create model elements corresponding to toolbox items.
				using (DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{
					// Retrieve the specified ToolboxItem from the DSL
					this.toolboxItemCache[itemId] = item = this.GetToolboxItem(itemId, store);
				}
			}

			return item;
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		public virtual object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			DslDesign::ModelingToolboxItem item = null;

			global::System.Resources.ResourceManager resourceManager = global::Company.DSLBootstrap.DSLBootstrapDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;

			System.Windows.Forms.IDataObject tbxDataObj;

			//get the toolbox item
			item = GetToolboxItem(itemId);

			if (item != null)
			{
				ToolboxItemContainer container = new ToolboxItemContainer(item);
				tbxDataObj = container.ToolboxData;

				if (tbxDataObj.GetDataPresent(format.Name))
				{
					return tbxDataObj.GetData(format.Name);
				}
				else 
				{
					string invalidFormatString = resourceManager.GetString("UnsupportedToolboxFormat", resourceCulture);
					throw new InvalidOperationException(string.Format(resourceCulture, invalidFormatString, format.Name));
				}
			}

			string errorFormatString = resourceManager.GetString("UnresolvedToolboxItem", resourceCulture);
			throw new InvalidOperationException(string.Format(resourceCulture, errorFormatString, itemId));
		}		
	}
}
