//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.DSLBootstrap
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "mydsl2";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DSLBootstrap";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DSLBootstrapDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DSLBootstrapCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DSLBootstrapExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DSLBootstrapCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDSLBootstrapExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DSLBootstrapCommandSetId), 0x0001);
	
		// Package identifier
		public const string DSLBootstrapPackageId = "61852a7e-eae0-4084-a590-b3deea4bfcff";
		
		// Editor factory identifier
		public const string DSLBootstrapEditorFactoryId = "fec9c008-37fd-4a8b-81b7-4b66f6635418";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DSLBootstrapModelExplorerToolWindowId = "efb0bbbc-976e-4d5a-be16-5ed5bdefeba1";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.DSLBootstrap
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DSLBootstrapCommandSetId = "aa5f5aaa-7cdb-4eb1-a1fa-8ad186c48fee";
	}
}