//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using VSTextTemplatingHost = global::Microsoft.VisualStudio.TextTemplating.VSHost;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace Company.DSLBootstrap
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\10.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(DSLBootstrapExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(DSLBootstrapExplorerToolWindow), Constants.DSLBootstrapEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@DSLBootstrapToolboxTab;Company.DSLBootstrap.Dsl.dll", "Company.DSLBootstrap.DSLBootstrapToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@ButtonToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.ButtonToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Button", 
					"@ButtonToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@TableFormalToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.TableFormalToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TableFormal", 
					"@TableFormalToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@InnerFormalToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.InnerFormalToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"InnerFormal", 
					"@InnerFormalToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@EntradaToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.EntradaToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Entrada", 
					"@EntradaToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@EtiquetaToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.EtiquetaToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Etiqueta", 
					"@EtiquetaToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@BarradeprogresooToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.BarradeprogresooToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Barradeprogresoo", 
					"@BarradeprogresooToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@FormularioFormalToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.FormularioFormalToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"FormularioFormal", 
					"@FormularioFormalToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@FormularioBonitoToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.FormularioBonitoToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"FormularioBonito", 
					"@FormularioBonitoToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@CheckBoxToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.CheckBoxToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CheckBox", 
					"@CheckBoxToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@ItemToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.ItemToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Item", 
					"@ItemToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@ColumnaToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.ColumnaToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Columna", 
					"@ColumnaToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@RenglonToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.RenglonToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Renglon", 
					"@RenglonToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@InnerBonitoToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.InnerBonitoToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"InnerBonito", 
					"@InnerBonitoToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@TableBonitaToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.TableBonitaToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TableBonita", 
					"@TableBonitaToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@RadioButtonToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.RadioButtonToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"RadioButton", 
					"@RadioButtonToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@TextRowToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.TextRowToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TextRow", 
					"@TextRowToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@SelectItemToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.SelectItemToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SelectItem", 
					"@SelectItemToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@ColumnaRenglonToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.ColumnaRenglonToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ColumnaRenglon", 
					"@ColumnaRenglonToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@ButtonPrimaryToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.ButtonPrimaryToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ButtonPrimary", 
					"@ButtonPrimaryToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@ButtonWarningToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.ButtonWarningToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ButtonWarning", 
					"@ButtonWarningToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@ButtonSuccessToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.ButtonSuccessToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ButtonSuccess", 
					"@ButtonSuccessToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@ButtonInfoToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.ButtonInfoToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ButtonInfo", 
					"@ButtonInfoToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@ButtonDangerToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.ButtonDangerToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ButtonDanger", 
					"@ButtonDangerToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@EntradaEmailToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.EntradaEmailToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EntradaEmail", 
					"@EntradaEmailToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.DSLBootstrap.DSLBootstrapToolboxTab",
					"@EntradaPasswordToolboxItem;Company.DSLBootstrap.Dsl.dll", 
					"Company.DSLBootstrap.EntradaPasswordToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EntradaPassword", 
					"@EntradaPasswordToolboxBitmap;Company.DSLBootstrap.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideEditorFactory(typeof(DSLBootstrapEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(DSLBootstrapEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"DSLBootstrap", typeof(DSLBootstrapEditorFactory))]
	internal abstract partial class DSLBootstrapPackageBase : DslShell::ModelingPackage
	{
		protected global::Company.DSLBootstrap.DSLBootstrapToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new DSLBootstrapEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::Company.DSLBootstrap.DSLBootstrapToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			DSLBootstrapCommandSet commandSet = new DSLBootstrapCommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			DSLBootstrapClipboardCommandSet clipboardCommandSet = new DSLBootstrapClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(DSLBootstrapExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace Company.DSLBootstrap
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[VSTextTemplatingHost::ProvideDirectiveProcessor(typeof(global::Company.DSLBootstrap.DSLBootstrapDirectiveProcessor), global::Company.DSLBootstrap.DSLBootstrapDirectiveProcessor.DSLBootstrapDirectiveProcessorName, "A directive processor that provides access to DSLBootstrap files")]
	[global::System.Runtime.InteropServices.Guid(Constants.DSLBootstrapPackageId)]
	internal sealed partial class DSLBootstrapPackage : DSLBootstrapPackageBase
	{
	}
}